version: "3"

services:
  server:
    build: ./
    depends_on:
      - db
    environment:
      - SERVER_PORT=8080
      - CLIENT_WEB_PORT=8081
    ports:
      - "8080:8080"
    networks:
      - back-tier

  client_mobile:
    build: ./Mobile_version
    depends_on:
      - server
    volumes:
      - common:/apk

  client_web:
    build: ./AREA_FRONT
    depends_on:
      - server
      - client_mobile
    ports:
      - "8081:8081"
    volumes:
      - common:/apk

  db:
    image: mongo:latest
    volumes:
      - db-data:/data/db
    networks:
      - back-tier
    restart: unless-stopped

networks:
  back-tier:

volumes:
  common:
  db-data: